# Generated by Django 5.0.6 on 2024-06-27 11:45

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_coverimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
