# Generated by Django 5.0.6 on 2024-06-02 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_author_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
