# Generated by Django 5.0.6 on 2024-06-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_reply_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
