# Generated by Django 5.0.6 on 2024-06-03 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_reply_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='title',
        ),
    ]
