# Generated by Django 5.0.6 on 2024-06-03 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_reply_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reply',
            new_name='Replsy',
        ),
    ]
