# Generated by Django 5.0.6 on 2024-06-03 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_rename_reply_replsy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Replsy',
            new_name='Reply',
        ),
    ]
