# Generated by Django 5.0.6 on 2024-06-03 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_remove_reply_comment_rename_blog_blogsad_commentsad_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blogsad',
            new_name='Blog',
        ),
        migrations.RenameModel(
            old_name='Commentsad',
            new_name='Comments',
        ),
        migrations.RenameModel(
            old_name='Replyad',
            new_name='Reply',
        ),
    ]
