# Generated by Django 5.0.6 on 2024-06-03 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_rename_blogsad_blog_rename_commentsad_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='secondaryId',
        ),
    ]
