# Generated by Django 5.0.6 on 2024-06-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_remove_reply_secondaryid'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='totalComments',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
