# Generated by Django 5.0.6 on 2024-06-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_comments_totalcomments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='totalComments',
        ),
        migrations.AddField(
            model_name='blog',
            name='totalComments',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
