# Generated by Django 5.0.6 on 2024-06-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_remove_comments_totalcomments_blog_totalcomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='likes',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
