# Generated by Django 5.0.6 on 2024-06-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_blog_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='totalReplies',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
