# Generated by Django 5.0.6 on 2024-06-05 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_alter_blog_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='secondaryId',
        ),
    ]
