# Generated by Django 5.0.6 on 2024-06-05 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_remove_comments_secondaryid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='coverImage',
            field=models.ImageField(upload_to='static/Blog'),
        ),
    ]
