# Generated by Django 5.0.6 on 2024-06-05 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_alter_blog_coverimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='total_likes',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='likes',
            field=models.BooleanField(default=False),
        ),
    ]
