# Generated by Django 5.0.6 on 2024-06-05 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_blog_total_likes_alter_blog_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='likes',
        ),
    ]
