# Generated by Django 5.0.6 on 2024-06-06 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_remove_blog_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='comments',
            new_name='reply',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='title',
        ),
    ]
