# Generated by Django 5.0.6 on 2024-06-06 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_rename_comments_reply_reply_remove_comments_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Blogs',
        ),
        migrations.RenameModel(
            old_name='Comments',
            new_name='Commentss',
        ),
        migrations.RenameModel(
            old_name='Reply',
            new_name='Replys',
        ),
    ]
